import test from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPairSync,sign} from 'node:crypto';
import {V2_POLICY,canonical,assumptionPayload,verifyAssumptionEvidence,designFingerprint,auditInput,analyze,populationRatioBound,populationSharedDifferenceBound,populationRiskDifferenceBound,syntheticLedger,exactClusterGridControls,runSimulationControls} from '../src/analysis-v04-v2.mjs';
const identities=['independent-owner','independent-audit'].map(role=>({role,authorityId:`synthetic-${role}`,...generateKeyPairSync('ed25519')}));
const context={trustDomain:'synthetic-control',analysisAuthorIds:['analysis-author'],trustedAuthorities:identities.map(x=>({role:x.role,authorityId:x.authorityId,publicKeyPem:x.publicKey.export({type:'spki',format:'pem'}).toString()}))};
function signed(input,overrides={}){const payload=assumptionPayload(input,{trustDomain:'synthetic-control',lockedAt:'2026-01-01T00:00:00Z',positiveDenominators:['R:eligible'],evidenceRefs:['source-family-dependence','execution-independence','frame-bound','pre-outcome-lock'].map(purpose=>({purpose,reference:'synthetic-control-evidence-only',sha256:'a'.repeat(64)})),...overrides});input.assumptionEvidence={payload,signatures:identities.map(x=>({role:x.role,authorityId:x.authorityId,signatureBase64:sign(null,Buffer.from(canonical(payload)),x.privateKey).toString('base64')}))};return input;}
const reject=r=>{r.proposal={status:'methodRejection',candidateHash:'a'.repeat(64),scopeGuardRejected:false,invoked:true,acceptanceLocked:false};r.outcomes={R:null,G:null};};
const outcome=classification=>({confirmedViolation:classification==='W',unknown:classification==='U_A',allRequiredPassed:classification==='S',binding:{evaluationSchema:'synthetic-evaluation-1',normalizerVersion:'synthetic-normalizer-1',evidenceHash:'e'.repeat(64),classification}});

test('observed A0 null is distinct from population no-information [0,1]',()=>{const b=populationRatioBound(Array.from({length:48},()=>({n:0,d:0})),Array(48).fill(8));assert.equal(b.observedRatio,null);assert.deepEqual(b.interval,[0,1]);assert.equal(b.status,'population-no-information');assert.match(b.parameterDomain,/expected denominator/);});
test('observed W0 with positive acceptance never proves population risk zero',()=>{const b=populationRatioBound(Array.from({length:48},()=>({n:0,d:8})),Array(48).fill(8));assert.equal(b.observedRatio,0);assert.ok(b.interval[1]>0);});
test('sparse acceptance all wrong includes population risk one even on zero observed A',()=>{for(const successes of [0,1,2,48]){const rows=Array.from({length:48},(_,i)=>({n:i<successes?8:0,d:i<successes?8:0}));assert.equal(populationRatioBound(rows,Array(48).fill(8)).interval[1],1);}});
test('fixed denominator Hoeffding radius uses actual family capacities',()=>{const rows=[{n:8,d:8},{n:0,d:48}],alpha=.05/3,b=populationRatioBound(rows,[8,48],{alpha,fixedDenominator:true});assert.equal(b.radius,Math.sqrt((64+2304)*Math.log(2/alpha)/2));assert.equal(b.observedRatio,1/7);assert.deepEqual(b.capacities,[8,48]);});
test('shared denominator signed paired bound is symmetric and never task independent',()=>{const rows=Array.from({length:48},(_,i)=>[i<20?8:0,8,i<25?8:0,8]),caps=Array(48).fill(8),a=populationSharedDifferenceBound(rows,caps,{fixedDenominator:true}),b=populationSharedDifferenceBound(rows.map(([x,d,y,e])=>[y,e,x,d]),caps,{fixedDenominator:true});assert.ok(Math.abs(a.observedDifference+5/48)<1e-15);assert.ok(Math.abs(a.interval[0]+b.interval[1])<1e-15);assert.equal(a.K,48);});
test('shared denominator weak/zero observations get population [-1,1]',()=>{const rows=Array.from({length:48},()=>[0,0,0,0]),b=populationSharedDifferenceBound(rows,Array(48).fill(8));assert.equal(b.observedDifference,null);assert.deepEqual(b.interval,[-1,1]);assert.throws(()=>populationSharedDifferenceBound([[1,2,1,3]],[8]));});
test('different accepted populations use four-mean joint bound, not common A',()=>{const rows=Array.from({length:48},(_,i)=>[i<1?8:0,i<1?8:0,i<20?8:0,8]),b=populationRiskDifferenceBound(rows,Array(48).fill(8));assert.equal(b.full.alpha,.025);assert.equal(b.other.alpha,.025);assert.equal(b.full.interval[1],1);assert.ok(b.interval[0]>=-1&&b.interval[1]<=1);});
test('invalid rows, false caps, alpha and zero fixed denominator fail closed',()=>{assert.throws(()=>populationRatioBound([{n:0,d:0}],[8],{fixedDenominator:true}));assert.throws(()=>populationRatioBound([{n:9,d:9}],[8]));assert.throws(()=>populationRatioBound([{n:2,d:1}],[8]));assert.throws(()=>populationRatioBound([{n:0,d:1}],[1],{alpha:0}));});
test('unsigned author verified boolean cannot authorize any primary bound',()=>{const input=syntheticLedger();input.design.independence.status='verified';input.assumptionEvidence={verified:true};const r=analyze(input);assert.equal(r.assumptionGate.verified,false);for(const p of Object.values(r.population.primary))assert.equal(p.interval,null);assert.equal(r.observed.R.methods.FULL.rates.S_over_P,1);});
test('two detached independent signatures authorize only frozen declared target',()=>{const input=signed(syntheticLedger());const r=analyze(input,context);assert.equal(r.assumptionGate.verified,true);assert.equal(Object.keys(r.population.primary).length,3);for(const p of Object.values(r.population.primary)){assert.equal(p.alpha,.05/3);assert.ok(p.interval);}assert.equal(r.assumptionGate.target,'locked-design-cluster-expectations');});
test('ledger signatures without external trust anchors do not authorize inference',()=>{const input=signed(syntheticLedger());assert.equal(verifyAssumptionEvidence(input).verified,false);input.trustedAuthorities=context.trustedAuthorities;assert.equal(verifyAssumptionEvidence(input).verified,false);});
test('author identity, same key, missing auditor and tampered payload are rejected',()=>{const input=signed(syntheticLedger());assert.equal(verifyAssumptionEvidence(input,{...context,analysisAuthorIds:[identities[0].authorityId]}).verified,false);const duplicate={...context,trustedAuthorities:[context.trustedAuthorities[0],{...context.trustedAuthorities[1],publicKeyPem:context.trustedAuthorities[0].publicKeyPem}]};assert.equal(verifyAssumptionEvidence(input,duplicate).verified,false);const missing=structuredClone(input);missing.assumptionEvidence.signatures.pop();assert.equal(verifyAssumptionEvidence(missing,context).verified,false);input.assumptionEvidence.payload.K=999;assert.equal(verifyAssumptionEvidence(input,context).verified,false);});
test('signed wrong target/alpha/weight/K/L/design cannot silently change estimands',()=>{for(const name of ['target','weight','K','L','familyAlpha']){const input=signed(syntheticLedger());input.assumptionEvidence.payload[name]=name==='target'||name==='weight'?'wrong':42;input.assumptionEvidence.signatures=identities.map(x=>({role:x.role,authorityId:x.authorityId,signatureBase64:sign(null,Buffer.from(canonical(input.assumptionEvidence.payload)),x.privateKey).toString('base64')}));assert.equal(verifyAssumptionEvidence(input,context).verified,false);}const input=signed(syntheticLedger());input.design.briefs[0].clusterId='changed';assert.equal(verifyAssumptionEvidence(input,context).verified,false);});
test('pre-outcome lock and substantive evidence references cannot be omitted',()=>{assert.equal(verifyAssumptionEvidence(signed(syntheticLedger(),{lockedAt:'2026-01-03T00:00:00Z'}),context).verified,false);assert.equal(verifyAssumptionEvidence(signed(syntheticLedger(),{evidenceRefs:[]}),context).verified,false);});
test('S/E primary needs signed population positivity, not observed positive E alone',()=>{const r=analyze(signed(syntheticLedger(),{positiveDenominators:[]}),context);assert.equal(r.assumptionGate.verified,true);assert.equal(r.population.primary['R/FULL/S_over_E'].interval,null);assert.ok(r.population.primary['R/FULL/S_over_P'].interval);});
test('formal 96 briefs with 48 true dependency families is structurally valid',()=>{const input=syntheticLedger(96);input.datasetKind='formal';input.design.maxBriefsPerCluster=2;input.design.briefs.forEach((b,i)=>b.clusterId=`family-${Math.floor(i/2)}`);assert.equal(auditInput(input).valid,true);assert.equal(auditInput(input).clusterCount,48);assert.equal(verifyAssumptionEvidence(signed(input),context).verified,false);input.design.briefs.pop();assert.equal(auditInput(input).valid,false);});
test('functional labels do not overwrite highest dependency cluster binding',()=>{const input=syntheticLedger(4);input.design.briefs.forEach((b,i)=>{b.clusterId=`dependency-${Math.floor(i/2)}`;b.functionalFamily='shared-functional-label';});input.design.maxBriefsPerCluster=2;const r=analyze(signed(input),context);assert.equal(r.audit.clusterCount,2);assert.deepEqual(r.population.primary['R/FULL/S_over_P'].capacities,[16,16]);});
test('zero observed acceptance stays null descriptively, population bound [0,1] with valid evidence',()=>{const input=syntheticLedger();input.records.forEach(reject);const r=analyze(signed(input),context);assert.equal(r.observed.R.methods.FULL.rates.W_over_A,null);assert.deepEqual(r.population.pointwise.R.FULL.W_over_A.interval,[0,1]);assert.equal(r.exploratory.R.FULL.W_over_A.interval,null);});
test('scope candidate missing is never prevented harm; uncertainty and costs retained',()=>{const input=syntheticLedger();reject(input.records[0]);input.records[0].proposal.scopeGuardRejected=true;input.records[1].outcomes={R:outcome('W'),G:outcome('U_A')};reject(input.records[4]);reject(input.records[5]);input.records[4].proposal.candidateHash=null;input.records[5].proposal.candidateHash=null;const r=analyze(input);assert.equal(r.observed.R.scopeAblation.counts.preventedW,1);assert.equal(r.observed.G.scopeAblation.counts.unknown,1);assert.equal(r.observed.R.scopeAblation.counts.noCandidate,1);assert.equal(r.costs.activeHumanSeconds.total,null);});
test('missing duplicate unexpected and no-invocation remain distinct audited states',()=>{const input=syntheticLedger();input.records.shift();input.records.push(structuredClone(input.records[0]));const a=auditInput(input);assert.equal(a.missing.length,1);assert.equal(a.duplicates.length,1);assert.equal(analyze(input).population,null);const fresh=syntheticLedger();fresh.records[0].proposal={status:'notExecuted',candidateHash:null,scopeGuardRejected:false,invoked:false,acceptanceLocked:false};fresh.records[0].outcomes={R:null,G:null};const r=analyze(fresh);assert.equal(r.audit.notInvoked.length,1);assert.equal(r.observed.R.methods.FULL.counts.proposalNotExecuted,1);});
test('R/G are one patch with two masks, no denominator pooling',()=>{const input=syntheticLedger();for(const r of input.records.slice(0,4)){r.eligibility.G='originalIneligible';r.outcomes.G=null;}const r=analyze(input);assert.equal(r.observed.R.methods.FULL.counts.E,16);assert.equal(r.observed.G.methods.FULL.counts.E,15);assert.equal(r.audit.plannedSlots,64);});
test('exact 60 grid enumeration is over clusters and minimum coverage meets bound',()=>{const grid=exactClusterGridControls();assert.equal(grid.gridCount,60);assert.equal(grid.allPass,true);assert.ok(grid.minCoverage>=.95-1e-12);for(const r of grid.rows)assert.ok(Math.abs(r.probabilitySum-1)<1e-10);});
test('seeded v2 simulation controls reproduce, including population-A0 counterexample',()=>{const a=runSimulationControls({replicates:3,bootstrapReplicates:199,seed:7}),b=runSimulationControls({replicates:3,bootstrapReplicates:199,seed:7});assert.deepEqual(a,b);assert.equal(a.scenarios.length,11);const sparse=a.scenarios.find(x=>x.name==='sparseAcceptanceAllWrong');assert.equal(sparse.finiteSample.coverage,1);assert.equal(sparse.finiteSample.reported,3);assert.equal(a.scenarios.find(x=>x.name==='zeroAcceptance').finiteSample.coverage,null);});

test('same cryptographic approval key cannot masquerade as two differently formatted public PEMs',()=>{const input=signed(syntheticLedger());const changed={...context,trustedAuthorities:[context.trustedAuthorities[0],{...context.trustedAuthorities[1],publicKeyPem:context.trustedAuthorities[0].publicKeyPem+'\n'}]};input.assumptionEvidence.signatures[1].signatureBase64=sign(null,Buffer.from(canonical(input.assumptionEvidence.payload)),identities[0].privateKey).toString('base64');assert.equal(verifyAssumptionEvidence(input,changed).verified,false);});
test('incomplete primary target family never advertises simultaneous coverage',()=>{const r=analyze(signed(syntheticLedger(),{positiveDenominators:[]}),context);assert.equal(r.population.primaryFamily.complete,false);assert.equal(r.population.primaryFamily.nominalFamilyCoverage,null);const full=analyze(signed(syntheticLedger()),context);assert.equal(full.population.primaryFamily.complete,true);assert.equal(full.population.primaryFamily.nominalFamilyCoverage,.95);});
test('malformed assumption evidence returns blocked rather than escaping analysis',()=>{const input=syntheticLedger();input.assumptionEvidence={payload:{target:undefined},signatures:[null,null]};const gate=verifyAssumptionEvidence(input,context);assert.equal(gate.verified,false);assert.ok(gate.reasons.length);});
