import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {loadCalibratedPolicyR2,publicLocatorR2,createScenarioLifecycleR2,createObservationCollectorR2,evaluateCheckR2,runScenarioR2,scenarioCheckKeyR2,validateBoundBaselineR2,BOUND_BASELINE_SCHEMA} from '../src/evaluate-adapter-r2.mjs';
import {APP_SCRIPT_ENTRY_CONTRACT} from '../src/entry-contract-r2.mjs';
import {validateMeasurementPolicy} from '../src/measurement-r2.mjs';
const hash=x=>createHash('sha256').update(x).digest('hex'),digest=x=>hash(JSON.stringify(x));
const observerHash='a'.repeat(64),revision='v04-observer-r2-fake-3',runtimeHashes={'react.umd.js':'b'.repeat(64),'react-dom.umd.js':'c'.repeat(64)};
const version={protocolVersion:'1.3',product:'Fake/1',revision:'unit',userAgent:'fake-only',jsVersion:'0'};
function policyData(){const body={schema:'r2-sparse-native-witness-v1',browserVersion:version,observerSha256:observerHash,runnerSha256:'d'.repeat(64),fixtureHashes:{html:'e'.repeat(64),jsx:'f'.repeat(64)},runtimeHashes,rules:[{ruleId:'text-empty',browserVersionKey:digest(Object.fromEntries(Object.entries(version).sort(([a],[b])=>a.localeCompare(b)))),type:'input:text',emptyMeansEmpty:true,validated:true,emptyEncoding:{textValue:'entry-absent',inputValue:'string-index-minus-one',axValue:'absent'},emptyWitnessCount:8,nonemptyWitnessCount:8}]};return{...body,policyId:'r2-sparse-'+digest(body)}}
async function binding(modify,overrides={}){const p=policyData();modify?.(p);const bytes=Buffer.from(JSON.stringify(p));return loadCalibratedPolicyR2({policyPath:'PUBLIC-FAKE-CALIBRATION.json',expectedFileSha256:hash(bytes),expectedObserverSha256:observerHash,expectedObserverRevision:revision,expectedRuntimeHashes:runtimeHashes,readBytes:async()=>bytes,...overrides})}
class Clock{
 constructor(){this.time=0;this.timers=[]}now=()=>this.time;
 sleep=(ms,signal)=>new Promise((resolve,reject)=>{if(signal?.aborted){reject(new Error('aborted'));return}const t={at:this.time+ms,active:true};const abort=()=>{if(t.active){t.active=false;reject(new Error('aborted'))}};t.finish=()=>{t.active=false;signal?.removeEventListener('abort',abort);resolve()};signal?.addEventListener('abort',abort,{once:true});this.timers.push(t)});
 async run(promise){let done=false,result,error;promise.then(v=>{done=true;result=v},e=>{done=true;error=e});for(let turn=0;turn<10000&&!done;turn++){for(let i=0;i<60;i++)await Promise.resolve();if(done)break;const pending=this.timers.filter(t=>t.active);assert.ok(pending.length,'pending fake operation needs wakeup');this.time=Math.max(this.time,Math.min(...pending.map(t=>t.at)));for(const t of this.timers.filter(t=>t.active&&t.at<=this.time))t.finish()}assert.ok(done);if(error)throw error;return result}
}
const viewport={width:390,height:844},catalog={field:{by:'role',role:'textbox',name:'Public field',exact:true},button:{by:'role',role:'button',name:'Public button',exact:true}};
const policy={timeoutMs:200,pollIntervalMs:50,stableSamples:3,geometryDeltaPx:.5,cleanupTimeoutMs:30};
const check=(id='v',value='')=>({op:'observe',id,observation:{kind:'value',targetRef:'field'},expect:{cmp:'eq',value}});
function element(value=''){return{backendNodeId:17,tagName:'input',type:'input:text',visible:true,value,valueState:'available',source:['DOMSnapshot.inputValue'],rawPresence:{snapshotNode:true,axNode:true,axIgnored:false,hasLayout:true},attributes:{title:'public'},text:'Public text',enabled:true,boundingRect:{x:5,y:5,width:100,height:20}}}
class Session{
 constructor(calibration){this.calibration=calibration;this.calls=[];this.epoch=0;this.aborts=0;this.value='';this.pending=false;this.failure=null;this.receipt=null;this.inspectHook=null;this.actHook=null;this.renderHook=null;this.abortHook=null}
 get diagnostics(){return{renderEpoch:this.epoch,protocolFailure:this.failure,cleanupPending:this.pending,current:this.receipt,pageErrors:this.runtimeErrors??[]}}
 async render(request){this.calls.push(['render',request]);this.epoch++;this.failure=null;this.receipt={renderId:'render-'+this.epoch,renderEpoch:this.epoch,observerSha256:observerHash,observerRevision:revision,browserVersion:version,runtimeHashes,entryContract:request.entryContract??'html-srcdoc-shared-react-prefix-2'};return this.renderHook?this.renderHook(request):this.receipt}
 async inspect(request){this.calls.push(['inspect',request]);if(this.inspectHook)return this.inspectHook(request);return this.inspection()}
 inspection(elements=[element(this.value)],extra={}){return{renderId:this.receipt.renderId,renderEpoch:this.epoch,calibrationPolicyId:this.calibration.policyId,browserVersion:version,contextBackendNodeIds:[],matchCount:elements.length,elements,rawSampleId:'sample-'+this.calls.length,rawSamplePath:'PUBLIC-FAKE-RAW.json',capture:{startedMs:0,completedMs:1},...extra}}
 async act(request){this.calls.push(['act',request]);if(this.actHook)return this.actHook(request);if(request.action==='fill')this.value=request.value;return{performed:true}}
 async abortRender(){this.aborts++;this.epoch++;this.failure='aborted';this.pending=true;if(this.abortHook)return this.abortHook();this.pending=false}
}
function scenario(steps=[check()]){return{id:'case',suiteId:'suite',freshReload:true,assertNoHorizontalOverflow:false,steps}}
function renderRequest(format='html'){const sourceBytes=Buffer.from(format==='html'?'<input aria-label="Public field">':'function App(){return <input aria-label="Public field"/>}');return{sourceBytes,format,trustLevel:'restricted-generated',staticGate:{accepted:true,sourceSha256:hash(sourceBytes)},artifactId:'fake',viewport,...(format==='jsx'?{entryContract:APP_SCRIPT_ENTRY_CONTRACT}:{})}}
async function setup(){const calibration=await binding(),session=new Session(calibration),clock=new Clock();return{calibration,session,clock}}
async function run({steps=[check()],format='html',configure=()=>{},...extra}={}){const c=await setup();configure(c.session,c.clock);const s=scenario(steps),expectedKeys=s.steps.flatMap((x,i)=>x.op==='observe'?[scenarioCheckKeyR2(s,'desktop',i,x.id)]:[]);const result=await c.clock.run(runScenarioR2({...c,renderRequest:renderRequest(format),scenario:s,catalog,policy,expectedKeys,...extra}));return{...c,result}}

test('calibration loader binds exact bytes, observer revision/hash and runtime then deep freezes',async()=>{const c=await binding();assert.equal(c.observerRevision,revision);assert.ok(Object.isFrozen(c)&&Object.isFrozen(c.policy.rules[0]));assert.throws(()=>{c.policy.rules[0].validated=false},TypeError);await assert.rejects(binding(null,{expectedFileSha256:'0'.repeat(64)}),/FILE_HASH_MISMATCH/);await assert.rejects(binding(null,{expectedObserverSha256:'0'.repeat(64)}),/OBSERVER_MISMATCH/);await assert.rejects(binding(null,{expectedRuntimeHashes:{other:'0'.repeat(64)}}),/RUNTIME_MISMATCH/)});
test('policy booleans alone cannot authorize double omission or tampered rule bodies',async()=>{await assert.rejects(binding(p=>{p.rules[0].emptyEncoding.inputValue='entry-absent'}),/DIGEST_MISMATCH/);const p=policyData();p.rules[0].emptyEncoding.inputValue='entry-absent';const {policyId,...body}=p;p.policyId='r2-sparse-'+digest(body);const bytes=Buffer.from(JSON.stringify(p));await assert.rejects(loadCalibratedPolicyR2({policyPath:'fake',expectedFileSha256:hash(bytes),expectedObserverSha256:observerHash,expectedObserverRevision:revision,readBytes:async()=>bytes}),/RULE_INVALID/)});
test('public locators reject nested expectations, inexact lookup, arbitrary selectors and prototype tricks',()=>{assert.deepEqual(publicLocatorR2(catalog.field),catalog.field);for(const loc of [{...catalog.field,conditionExpected:'PRIVATE'},{...catalog.field,exact:false},{...catalog.field,within:{...catalog.button,expect:{cmp:'eq',value:'PRIVATE'}}},Object.assign(Object.create({injected:true}),catalog.field)])assert.throws(()=>publicLocatorR2(loc),/LOCATOR/)});
test('available empty actual passes through browser-string status to measurement object status',async()=>{const {result,session}=await run();assert.equal(result.classification.partition,'S');const m=result.checks[0].measurement;assert.equal(m.samples[0].actual,'');assert.equal(m.samples[0].evidence.valueState.status,'available');assert.equal(session.aborts,0)});
test('nonempty input and public fill clear actions follow declared replay without source execution',async()=>{const {result}=await run({steps:[{op:'fill',targetRef:'field',value:'seed'},check('seed','seed'),{op:'fill',targetRef:'field',value:''},check('clear','')]});assert.equal(result.classification.partition,'S');assert.equal(result.actions.length,2);assert.equal(result.checks[1].measurement.evidence.lastValid.actual,'')});
test('unknown input remains unknown with original code and no fabricated actual',async()=>{const {result}=await run({configure:s=>{s.inspectHook=async()=>s.inspection([{...element(),value:null,valueState:'unavailable',valueError:'VALUE_UNAVAILABLE_UNCALIBRATED_SENTINEL'}])}});assert.equal(result.classification.partition,'U_A');assert.ok(result.checks[0].measurement.samples.every(x=>x.state==='unknown'&&!Object.hasOwn(x,'actual')));assert.equal(result.checks[0].measurement.samples[0].error.code,'VALUE_UNAVAILABLE_UNCALIBRATED_SENTINEL')});
test('hidden empty and hidden nonempty both fail the same observability qualification',async()=>{for(const value of ['', 'seed']){const {result}=await run({steps:[check('hidden',value)],configure:s=>{s.inspectHook=async()=>s.inspection([{...element(value),visible:false}])}});assert.equal(result.classification.partition,'U_A');assert.equal(result.checks[0].measurement.samples[0].error.code,'OBSERVATION_TARGET_NOT_VISIBLE')}});
test('value text attribute rect count enabled and viewport primitives are explicit supported facts',async()=>{const observations=[['text',{kind:'text',targetRef:'field'},{cmp:'eq',value:'Public text'}],['attribute',{kind:'attribute',targetRef:'field',attribute:'missing'},{cmp:'eq',value:null}],['width',{kind:'rect',targetRef:'field',field:'width'},{cmp:'between',min:99,max:101}],['count',{kind:'count',targetRef:'field'},{cmp:'eq',value:1}],['enabled',{kind:'enabled',targetRef:'field'},{cmp:'eq',value:true}],['viewport',{kind:'withinViewport',targetRef:'field',axis:'x',tolerance:0},{cmp:'eq',value:true}]];const {result}=await run({steps:observations.map(([id,observation,expect])=>({op:'observe',id,observation,expect}))});assert.equal(result.classification.partition,'S');assert.equal(result.checks.length,6)});
test('unsupported compound geometry fails explicitly before any browser render',async()=>{const c=await setup();const s=scenario([{...check(),observation:{kind:'grid',targetRef:'field'}}]);await assert.rejects(runScenarioR2({...c,renderRequest:renderRequest(),scenario:s,catalog,policy,expectedKeys:[scenarioCheckKeyR2(s,'desktop',0,'v')]}),/R2_OBSERVATION_UNSUPPORTED/);assert.equal(c.session.calls.length,0)});
test('fatal codes survive bridge and force one abort plus explicit downstream notMeasured',async()=>{const {result,session}=await run({steps:[check('first'),{op:'click',targetRef:'button'},check('later')],configure:s=>{s.inspectHook=async()=>{throw Object.assign(new Error('lost'),{code:'SESSION_CLOSED'})}}});assert.equal(result.checks[0].measurement.termination.reason,'fatal-collection-error');assert.equal(result.checks[0].measurement.samples[0].error.code,'SESSION_CLOSED');assert.ok(result.checks[1].notMeasured);assert.equal(result.actions[0].status,'skipped');assert.equal(session.aborts,1);assert.equal(result.classification.partition,'U_A')});
test('stuck inspect is deadline bounded with single abort and immutable late evidence',async()=>{let settle;const {result,session}=await run({steps:[check('first'),check('later')],configure:s=>{s.inspectHook=()=>new Promise(resolve=>{settle=resolve})}});assert.equal(session.aborts,1);assert.ok(result.checks[1].notMeasured);const before=JSON.stringify(result);settle(session.inspection());for(let i=0;i<40;i++)await Promise.resolve();assert.equal(JSON.stringify(result),before);assert.equal(session.calls.filter(([op])=>op==='render').length,1)});
test('cleanup timeout blocks future render instead of reusing a still-cleaning session',async()=>{const {result,session,clock,calibration}=await run({configure:s=>{s.inspectHook=()=>new Promise(()=>{});s.abortHook=()=>new Promise(()=>{})}});assert.equal(result.checks[0].measurement.health.cleanup.status,'timeout');const count=session.calls.length,s=scenario();const second=await clock.run(runScenarioR2({session,clock,calibration,renderRequest:renderRequest(),scenario:s,catalog,policy,expectedKeys:[scenarioCheckKeyR2(s,'desktop',0,'v')]}));assert.equal(session.calls.length,count);assert.equal(session.aborts,1);assert.ok(second.checks[0].notMeasured);assert.equal(second.classification.partition,'U_A')});
test('late old inspect cannot contaminate a later fresh render',async()=>{let settle;const first=await run({configure:s=>{s.inspectHook=()=>new Promise(resolve=>{settle=resolve})}});const oldReceipt=first.result.receipt;first.session.inspectHook=null;const s=scenario(),pending=runScenarioR2({...first,session:first.session,clock:first.clock,calibration:first.calibration,renderRequest:renderRequest(),scenario:s,catalog,policy,expectedKeys:[scenarioCheckKeyR2(s,'desktop',0,'v')]});settle(first.session.inspection([element('stale')],{renderId:oldReceipt.renderId,renderEpoch:oldReceipt.renderEpoch}));const second=await first.clock.run(pending);assert.equal(second.classification.partition,'S');assert.equal(second.checks[0].measurement.evidence.lastValid.actual,'');assert.equal(first.session.aborts,1)});
test('private expectation/condition sentinel never enters render inspect or action payloads',async()=>{const sentinel='PRIVATE_EXPECTATION_CONDITION_SENTINEL';const {result,session}=await run({steps:[check('private',sentinel)]});assert.equal(result.classification.partition,'W');assert.ok(!JSON.stringify(session.calls).includes(sentinel));for(const [op,payload]of session.calls)if(op==='inspect')assert.deepEqual(Object.keys(payload),['locator']);const c=await setup();await c.session.render(renderRequest());const lifecycle=createScenarioLifecycleR2({...c,receipt:c.session.receipt});assert.throws(()=>createObservationCollectorR2({...c,observation:check().observation,catalog,viewport,lifecycle,expect:sentinel}),/PRIVATE_OR_UNKNOWN_COLLECTOR_FIELD/)});
test('context chain participates in stability identity and missing chain is unknown',async()=>{const scoped={field:{...catalog.field,within:{by:'role',role:'group',name:'Panel',exact:true}}};let count=0;const {result}=await run({catalog:scoped,policy:{...policy,timeoutMs:300},configure:s=>{s.inspectHook=async()=>s.inspection([element()],{contextBackendNodeIds:[++count<3?100:200]})}});assert.equal(result.classification.partition,'S');assert.equal(result.checks[0].measurement.samples.length,5);const missing=await run({catalog:scoped});assert.equal(missing.result.classification.partition,'U_A');assert.equal(missing.result.checks[0].measurement.samples[0].error.code,'LOCATOR_CONTEXT_IDENTITY_UNAVAILABLE')});
test('raw sample ids change only evidence, not stability identity',async()=>{const {result}=await run();const samples=result.checks[0].measurement.samples;assert.equal(samples.length,3);assert.notEqual(samples[0].evidence.rawSamples[0].id,samples[1].evidence.rawSamples[0].id);assert.deepEqual(samples[0].identity,samples[1].identity)});
test('formal expected keys are mandatory and independently checked before render',async()=>{const c=await setup(),s=scenario();await assert.rejects(runScenarioR2({...c,renderRequest:renderRequest(),scenario:s,catalog,policy}),/FORMAL_EXPECTED_KEYS_REQUIRED/);await assert.rejects(runScenarioR2({...c,renderRequest:renderRequest(),scenario:s,catalog,policy,expectedKeys:['wrong']}),/FORMAL_EXPECTED_KEYS_REQUIRED/);assert.equal(c.session.calls.length,0)});
test('formal JSX requires App contract and verifies returned mount contract',async()=>{assert.equal((await run({format:'jsx'})).result.classification.partition,'S');const c=await setup(),s=scenario(),request=renderRequest('jsx');request.entryContract='jsx-export-default-commonjs-react-1';await assert.rejects(runScenarioR2({...c,renderRequest:request,scenario:s,catalog,policy,expectedKeys:[scenarioCheckKeyR2(s,'desktop',0,'v')]}),/FORMAL_APP_SCRIPT_ENTRY_REQUIRED/);const bad=await run({format:'jsx',configure:s=>{s.renderHook=async()=>({...s.receipt,entryContract:'jsx-export-default-commonjs-react-1'})}});assert.equal(bad.result.classification.partition,'U_A');assert.ok(bad.result.checks[0].notMeasured)});
test('observer revision/hash mismatch fails render provenance and aborts before inspect',async()=>{const {result,session}=await run({configure:s=>{s.renderHook=async()=>({...s.receipt,observerRevision:'legacy'})}});assert.equal(result.classification.partition,'U_A');assert.equal(session.aborts,1);assert.equal(session.calls.filter(([op])=>op==='inspect').length,0)});
test('render and action budgets are separately bounded and do not fabricate check failures',async()=>{for(const phase of ['render','action']){const {result,session,clock}=await run({steps:[{op:'click',targetRef:'button'},check()],renderTimeoutMs:100,actionTimeoutMs:100,configure:s=>{if(phase==='render')s.renderHook=()=>new Promise(()=>{});else s.actHook=()=>new Promise(()=>{})}});assert.equal(clock.time,100);assert.equal(session.aborts,1);assert.equal(result.classification.partition,'U_A');assert.ok(result.checks[0].notMeasured)}});
test('bound baseline requires all source replay locator viewport observer policy and checkpoint pins',()=>{const p={sourceSha256:'1'.repeat(64),replayDigest:'2'.repeat(64),catalogDigest:'3'.repeat(64),viewportDigest:'4'.repeat(64),observerSha256:'5'.repeat(64),observerRevision:revision,calibrationPolicyId:'policy',measurementPolicyDigest:'6'.repeat(64),checkpointKey:'checkpoint',entryContract:APP_SCRIPT_ENTRY_CONTRACT};const b={schemaVersion:BOUND_BASELINE_SCHEMA,actual:'seed',provenance:p};assert.equal(validateBoundBaselineR2(b,p).actual,'seed');for(const key of Object.keys(p)){const changed={...p,[key]:key.endsWith('Digest')||key.endsWith('Sha256')?'f'.repeat(64):'different'};assert.throws(()=>validateBoundBaselineR2(b,changed),/PROVENANCE_MISMATCH/)}assert.throws(()=>validateBoundBaselineR2({...b,schemaVersion:'v03-external-scenarios-1'},p),/BOUND_BASELINE_REQUIRED/)});
test('sameAsBaseline without bound provenance stays notMeasured rather than using r1 evidence',async()=>{const {result}=await run({steps:[{...check(),expect:{cmp:'sameAsBaseline',tolerance:0}}]});assert.equal(result.classification.partition,'U_A');assert.ok(result.checks[0].notMeasured);assert.equal(result.checks[0].notMeasured.error.code,'R2_BOUND_BASELINE_REQUIRED')});

test('late render completion cannot beat a delayed timeout callback',async()=>{const {result,session}=await run({renderTimeoutMs:100,configure:(s,clock)=>{s.renderHook=async()=>{clock.time=101;return s.receipt}}});assert.equal(result.classification.partition,'U_A');assert.equal(result.errors[0].error.code,'SCENARIO_STAGE_TIMEOUT');assert.equal(session.calls.filter(([op])=>op==='inspect').length,0);assert.equal(session.aborts,1)});
test('render receipt runtime error and asynchronous diagnostic runtime error both invalidate measurement',async()=>{const first=await run({configure:s=>{s.renderHook=async()=>({...s.receipt,pageErrors:[{description:'fixture error'}]})}});assert.equal(first.result.classification.partition,'U_A');assert.equal(first.result.errors[0].error.code,'PAGE_RUNTIME_ERROR');const second=await run({configure:s=>{s.inspectHook=async()=>{s.runtimeErrors=[{description:'async fixture error'}];return s.inspection()}}});assert.equal(second.result.classification.partition,'U_A');assert.equal(second.result.checks[0].measurement.samples[0].error.code,'PAGE_RUNTIME_ERROR');assert.equal(second.session.aborts,1)});
test('count zero remains a valid observed fact rather than a missing unique-target value',async()=>{const {result}=await run({steps:[{op:'observe',id:'zero',observation:{kind:'count',targetRef:'field'},expect:{cmp:'eq',value:0}}],configure:s=>{s.inspectHook=async()=>s.inspection([])}});assert.equal(result.classification.partition,'S');assert.equal(result.checks[0].measurement.evidence.lastValid.actual,0)});
test('invalid expectation schema is rejected before any formal rendering',async()=>{const c=await setup(),s=scenario([{...check(),expect:{cmp:'eq',value:'x',conditionExpected:'PRIVATE'}}]);await assert.rejects(runScenarioR2({...c,renderRequest:renderRequest(),scenario:s,catalog,policy,expectedKeys:[scenarioCheckKeyR2(s,'desktop',0,'v')]}),/INVALID_MEASUREMENT_EXPECTATION/);assert.equal(c.session.calls.length,0)});
test('bound baseline integrates through comparison with explicit original-source provenance',async()=>{const steps=[{...check(),expect:{cmp:'sameAsBaseline',tolerance:0}}],s=scenario(steps),key=scenarioCheckKeyR2(s,'desktop',0,'v'),originalSource='1'.repeat(64);const provenance={sourceSha256:originalSource,replayDigest:digest([]),catalogDigest:digest(catalog),viewportDigest:digest(viewport),observerSha256:observerHash,observerRevision:revision,calibrationPolicyId:policyData().policyId,measurementPolicyDigest:digest(validateMeasurementPolicy(policy)),checkpointKey:key,entryContract:'html-srcdoc-shared-react-prefix-2'};const baselineEvidence={[key]:{schemaVersion:BOUND_BASELINE_SCHEMA,actual:'',provenance}};const good=await run({steps,baselineEvidence,baselineSourceSha256:originalSource});assert.equal(good.result.classification.partition,'S');const mismatch=await run({steps,baselineEvidence});assert.equal(mismatch.result.classification.partition,'U_A');assert.equal(mismatch.result.checks[0].notMeasured.error.code,'R2_BASELINE_PROVENANCE_MISMATCH')});
