import test from 'node:test';
import assert from 'node:assert/strict';
import {LAYOUT_COMPUTED_PROPERTIES,pixelLength,resolvedTrackSizes,rectFromBounds,deriveGapFacts,deriveGridFacts,deriveOrderFacts,deriveBoxGapFacts,deriveVisualGridFacts,deriveQueryOrderFacts,deriveDocumentOverflowFacts,snapshotLayoutFacts} from '../src/layout-facts-r3.mjs';
const box=(x,y,w=20,h=20)=>rectFromBounds([x,y,w,h]);
function fixture({display='flex',positions=[[0,0],[100,0],[200,0]],orders=[2,1,3]}={}){
 const parent={documentIndex:0,nodeIndex:1,backendNodeId:10,parentBackendNodeId:1,ancestorBackendNodeIds:[1],computed:{display,'column-gap':'12px','row-gap':'8px','grid-template-columns':'80px 100px','grid-template-rows':'30px 40px','writing-mode':'horizontal-tb',direction:'ltr'},layout:{visible:true,bounds:box(0,0,300,100)}};
 const children=positions.map(([x,y],i)=>({documentIndex:0,nodeIndex:i+2,backendNodeId:i+11,parentBackendNodeId:10,ancestorBackendNodeIds:[10,1],computed:{order:String(orders[i]),'margin-left':'0px','margin-right':'0px','margin-top':'0px','margin-bottom':'0px'},layout:{visible:true,bounds:box(x,y)},layoutContexts:[{backendNodeId:10,parentBackendNodeId:1,computed:parent.computed,bounds:parent.layout.bounds}]}));
 return{state:'ok',facts:{targets:[['p',parent],...children.map((n,i)=>[['a','b','c'][i],n])].map(([key,n])=>({key,matchCount:1,nodes:[n]})),document:{contentWidth:390,contentHeight:1000,viewport:{width:390,height:844},scrollOffsetX:0,scrollOffsetY:0,dimensionsSource:'native-test'}}};
}
test('computed pixel values reject unresolved percentages/calc and parse named used tracks',()=>{assert.equal(pixelLength('12px'),12);assert.equal(pixelLength('normal',{normalZero:true}),0);assert.equal(pixelLength('7%'),null);assert.deepEqual(resolvedTrackSizes('[start] 80px [middle] 100px [end]'),[80,100]);assert.equal(resolvedTrackSizes('repeat(2, 1fr)'),null);assert.equal(resolvedTrackSizes('subgrid [x] [y]'),null);assert.equal(rectFromBounds([1,2,NaN,4]),null)});
test('CSS gap and visible edge spacing are different facts and both retain layout context',()=>{const f=fixture(),css=deriveGapFacts(f,{containerKey:'p',fromKey:'a',toKey:'b'}),visible=deriveBoxGapFacts(f,{fromKey:'a',toKey:'b',axis:'horizontal'});assert.equal(css.facts.columnPx,12);assert.equal(css.facts.pair.horizontalSignedPx,80);assert.equal(visible.facts.separationPx,80);assert.equal(visible.facts.cssGap.column,'12px');assert.equal(visible.facts.context.computed.display,'flex')});
test('visible gap is query-order independent while ordered signed displacement is retained',()=>{const f=fixture();const ab=deriveBoxGapFacts(f,{fromKey:'a',toKey:'b',axis:'horizontal'}),ba=deriveBoxGapFacts(f,{fromKey:'b',toKey:'a',axis:'horizontal'});assert.equal(ab.facts.separationPx,ba.facts.separationPx);assert.equal(ba.facts.fromToSignedPx,-120);assert.equal(deriveBoxGapFacts(f,{fromKey:'a',toKey:'b',axis:'vertical'}).facts.separationPx,-20)});
test('visual grid accepts legitimate flex while CSS-grid diagnostics reject an impostor',()=>{const f=fixture();const visual=deriveVisualGridFacts(f,{itemKeys:['a','b','c'],gridClusterTolerancePx:0.5});assert.equal(visual.state,'ok');assert.equal(visual.facts.columnCount,3);assert.equal(visual.facts.rowCount,1);assert.equal(deriveGridFacts(f,{containerKey:'p'}).error.code,'DOMAIN_GRID_CONTAINER_NOT_GRID');assert.equal(deriveGridFacts(fixture({display:'grid'}),{containerKey:'p'}).facts.columnCount,2)});
test('fixed complete-link clustering does not transitively merge a drifting row',()=>{const f=fixture({positions:[[0,0],[100,0.4],[200,0.8]]});const v=deriveVisualGridFacts(f,{itemKeys:['a','b','c'],gridClusterTolerancePx:0.5});assert.equal(v.facts.rowCount,2);assert.deepEqual(v.facts.rows.map(r=>r.keys),[['a','b'],['c']]);assert.equal(deriveVisualGridFacts(f,{itemKeys:['a'],gridClusterTolerancePx:NaN}).state,'unknown')});
test('visual and DOM order do not inherit the requested or CSS order',()=>{const f=fixture({positions:[[100,0],[0,0],[200,0]]});assert.deepEqual(deriveQueryOrderFacts(f,{itemKeys:['c','b','a'],orderBasis:'dom'}).facts.orderedKeys,['a','b','c']);assert.deepEqual(deriveQueryOrderFacts(f,{itemKeys:['c','a','b'],orderBasis:'visual'}).facts.orderedKeys,['b','a','c']);assert.deepEqual(deriveOrderFacts(f,{containerKey:'p',itemKeys:['a','b','c']}).facts.cssOrderModified,['b','a','c'])});
test('visual ties, missing targets, nonvisible nodes and cross-document compounds stay unknown',()=>{const tied=fixture({positions:[[0,0],[0,0],[200,0]]});assert.equal(deriveQueryOrderFacts(tied,{itemKeys:['a','b'],orderBasis:'visual'}).error.code,'DOMAIN_VISUAL_ORDER_TIED');for(const mutate of [f=>f.facts.targets[1].matchCount=0,f=>f.facts.targets[1].nodes[0].layout.visible=false,f=>f.facts.targets[1].nodes[0].documentIndex=2]){const f=fixture();mutate(f);assert.equal(deriveBoxGapFacts(f,{fromKey:'a',toKey:'b',axis:'horizontal'}).state,'unknown')}});
test('document overflow uses native whole-document metrics, not child rectangle union',()=>{const f=fixture();f.facts.targets[1].nodes[0].layout.bounds=box(0,0,4000,4000);assert.equal(deriveDocumentOverflowFacts(f).facts.horizontalPx,0);assert.equal(deriveDocumentOverflowFacts(f).facts.verticalPx,156);f.facts.document.contentWidth=1600;assert.equal(deriveDocumentOverflowFacts(f).facts.horizontalPx,1210);delete f.facts.document.contentWidth;assert.equal(deriveDocumentOverflowFacts(f).state,'unknown')});
test('no snapshot/document encodings are guessed from absent fields',()=>{assert.throws(()=>snapshotLayoutFacts({},'frame'),/MALFORMED/);assert.throws(()=>snapshotLayoutFacts({strings:[],documents:[]},'frame'),/DOCUMENT_MISSING/)});

test('coherent native property list covers cascade colors/fonts and preserves decoder property indices',()=>{assert.deepEqual(LAYOUT_COMPUTED_PROPERTIES.slice(0,3),['visibility','display','opacity']);for(const property of ['color','background-color','font-size','font-weight','font-family','border-radius'])assert.ok(LAYOUT_COMPUTED_PROPERTIES.includes(property));assert.equal(new Set(LAYOUT_COMPUTED_PROPERTIES).size,LAYOUT_COMPUTED_PROPERTIES.length)});